#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ls='ls -F --color'
alias la='ls -alF --color'
alias h='history'
alias c='clear'
alias ..='cd ..'

alias apt-get='sudo apt-get'

alias py='ipython'

alias top='htop'
alias vi='vim'
alias svi='sudo vi'

alias nginxreload='sudo nginx -s reload'
alias nginxtest='sudo nginx -t'

alias ports='netstat -tulanp'

alias wget='wget -c'

alias df='df -H'
alias du='du -ch'

alias rs='python manage.py runserver'
alias fs='forego start'
alias shell='python manage.py shell_plus'
alias m='python manage.py'

alias d='docker'
alias dc='docker-compose'
alias dm='docker-machine'

eval "$(thefuck --alias)"

if [[ -s "/home/$USER/.gvm/scripts/gvm" ]]; then
  source "/home/$USER/.gvm/scripts/gvm"
fi

