#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1

export PATH="$PATH:$HOME/.rvm/bin:/usr/local/heroku/bin"

source /usr/local/bin/virtualenvwrapper.sh
