#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ls='ls -FG'
alias la='ls -alFG'
alias h='history'
alias c='clear'
alias ..='cd ..'

alias cp='cp -r'
alias scp='scp -r'
alias mkdir='mkdir -p'

alias apt-get='sudo apt-get'

alias systemctl='sudo systemctl'

alias myip='curl http://ifconfig.me/ip'

alias py='ipython'

alias top='htop'
alias vi='vim'
alias svi='sudo vi'

alias nginxreload='sudo nginx -s reload'
alias nginxtest='sudo nginx -t'

alias ports='netstat -tulanp'

alias wget='wget -c'

alias df='df -H'
alias du='du -ch'

alias rs='python manage.py runserver'
alias fs='forego start'
alias shell='python manage.py shell_plus'
alias m='python manage.py'

alias d='docker'
alias dc='docker-compose'
alias dm='docker-machine'

alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"

alias busy="cat /dev/urandom | hexdump -C"

eval "$(thefuck --alias)"

# make a backup of a file
# https://github.com/grml/grml-etc-core/blob/master/etc/zsh/zshrc
bk() {
  cp -a "$1" "${1}_$(date --iso-8601=seconds)"
}

if [[ -s "$HOME/.gvm/scripts/gvm" ]]; then
  source "$HOME/.gvm/scripts/gvm"
fi

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  source "$HOME/.rvm/scripts/rvm"
fi
